config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  post "/authenticate", action: :create, controller: :authentications
  post "/revoke", action: :revoke, controller: :authentications
  post "/refresh", action: :refresh, controller: :authentications
  post "/user", action: :create, controller: :users
  get "/users/:id", action: :show, controller: :users, as: :user_profile
  get "/user/me/password/:id", action: :password, controller: :users, as: :user_password
  post "/user/me/password", action: :change_password, controller: :users
  post "/users/reset_password", action: :reset_password, controller: :users
  put "/users/me", action: :update, controller: :users
  get "/user/my_widgets", action: :my_widgets, controller: :users
  get "/users/:id/widgets", action: :user_widget_index, controller: :users
  post "/widgets", action: :create, controller: :widgets
  put "/widgets/:id", action: :update, controller: :widgets
  get "/widgets", action: :index, controller: :widgets
  get "/visible_widgets", action: :visible, controller: :widgets
  delete "/widgets/:id", action: :destroy, controller: :widgets, as: :delete_widget
end

app/views/shared/_login.html.erb
<button type="button" class="btn btn-primary success" data-toggle="modal" data-target="#myModal">Login
</button>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag authenticate_path, method: :post do %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Please Login</h4>
        </div>
        <div class="modal-body">
          <div class="col-xs-8">
            <%= text_field_tag :email, "",class: "form-control", placeholder: "username" %>
            <%= password_field_tag :password, "",class: "form-control", placeholder: "password" %>
          </div>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary info">Login</button> -->
          <%= submit_tag "login", class: "btn btn-primary info"%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_tag(widgets_path, :method => "get") do %>
  <div class="form-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
    <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
  </div>
  </br>
<% end %>

app/views/shared/_signup.html.erb
<button type="button" class="btn btn-primary success" data-toggle="modal" data-target="#signup">
  Sign Up
</button>
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag user_path, :method => :post do %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
        </div>
        <div class="modal-body">
          <div class="col-xs-8">
            <%= text_field_tag 'user[first_name]', "",class: "form-control", placeholder: "First Name" %>
            <%= text_field_tag 'user[last_name]', "",class: "form-control", placeholder: "Last Name" %>
            <%= text_field_tag 'user[email]', "",class: "form-control", placeholder: "username" %>
            <%= hidden_field_tag 'user[image_url]', "https://static.thenounproject.com/png/961-200.png"%>
            <%= password_field_tag 'user[password]', "",class: "form-control", placeholder: "password" %>
          </div>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary info">Login</button> -->
          <%= submit_tag "login", class: "btn btn-primary info"%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_widget.html.erb
<div class="center jumbotron">
  <h1><%= widget['name']%></h1>
  <h2><%= widget['description']%></h2>
  <p>
    <% if widget['user'].present? %>
      Auther: <%= link_to widget['user']['name'], user_profile_path(widget['user']['id'])%>
    <% end %>
    <% if widget['user']['id'] == current_user_id %>
      <%= link_to 'delete', delete_widget_path(widget['id']), method: :delete%>
    <% end %>
  </p>
</div>

app/views/shared/_widget_form.html.erb
<%= form_tag widgets_path, method: :post do %>
  <div class="form-group">
    <label for="formGroupExampleInput">Name</label>
    <%= text_field_tag 'widget[name]', "",class: "form-control", placeholder: "name" %>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Description</label>
    <%= text_area_tag 'widget[description]', "",class: "form-control", placeholder: "Description" %>
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Visible</label>
    <%= check_box_tag 'widget[kind]', 'visible' %>
  </div>
  <%= submit_tag "Post", class: "btn btn-primary info"%>
<% end %>