config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  post "/authenticate", action: :create, controller: :authentications
  post "/revoke", action: :revoke, controller: :authentications
  post "/refresh", action: :refresh, controller: :authentications
  post "/user", action: :create, controller: :users
  get "/users/:id", action: :show, controller: :users, as: :user_profile
  get "/user/me/password/:id", action: :password, controller: :users, as: :user_password
  post "/user/me/password", action: :change_password, controller: :users
  post "/users/reset_password", action: :reset_password, controller: :users
  put "/users/me", action: :update, controller: :users
  get "/user/my_widgets", action: :my_widgets, controller: :users
  get "/users/:id/widgets", action: :user_widget_index, controller: :users
  post "/widgets", action: :create, controller: :widgets
  put "/widgets/:id", action: :update, controller: :widgets
  get "/widgets", action: :index, controller: :widgets
  get "/visible_widgets", action: :visible, controller: :widgets
  delete "/widgets/:id", action: :destroy, controller: :widgets, as: :delete_widget
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li>
            <%= link_to "Home", widgets_path %>
          </li>
          <li>
            <%= link_to "My Widgets", user_my_widgets_path%>
          </li>
          <li>
            <%= link_to "Profile", user_profile_path(current_user_id)%>
          </li>
          <li>
            <%= link_to "Logout", revoke_path, method: :post%>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShowoffRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= yield %>

</body>
</html>